project_id = "yphkfkpfdpdmllotpqua"

[functions.diag-universe-image]
verify_jwt = false

[functions.generate-universe-image]
verify_jwt = true

[functions.create-universe]
verify_jwt = true

[functions.image-service]
verify_jwt = false