project_id = "yphkfkpfdpdmllotpqua"

[functions.diag-universe-image]
verify_jwt = false

[functions.generate-universe-image]
verify_jwt = true
# Force redeploy to pick up IMAGE_PROVIDER secret

[functions.create-universe]
verify_jwt = true