project_id = "yphkfkpfdpdmllotpqua"

[functions.adventure-settings]
verify_jwt = true

[functions.cover-generator]
verify_jwt = false

[functions.generate-adventure-lesson]
verify_jwt = false

[functions.generate-adventure-multipart]
verify_jwt = false

[functions.realtime-chat]
verify_jwt = false
