
import { useState, useEffect } from "react";
import { useAuth } from "@/hooks/useAuth";
import { useNavigate } from "react-router-dom";
import { useAdaptiveLearning } from "@/hooks/useAdaptiveLearning";
import LearningHeader from "./LearningHeader";
import AILearningModule from "@/components/adaptive-learning/AILearningModule";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain } from "lucide-react";

const MathematicsLearning = () => {
  const {
    user,
    loading
  } = useAuth();
  const navigate = useNavigate();
  const [useAIQuestions, setUseAIQuestions] = useState(false);
  const [aiSessionKey, setAiSessionKey] = useState(0);

  console.log('🔢 MathematicsLearning component state:', {
    user: !!user,
    userId: user?.id,
    loading,
    useAIQuestions,
    aiSessionKey
  });

  const {
    difficulty,
    performanceMetrics,
    recommendedSessionTime,
    recordAnswer,
    adjustDifficulty,
    endSession
  } = useAdaptiveLearning('mathematics', 'arithmetic');

  // Redirect to auth if not logged in - but only after loading is complete
  useEffect(() => {
    console.log('🔍 Auth check effect:', {
      loading,
      hasUser: !!user
    });
    if (!loading && !user) {
      console.log("🚪 User not authenticated in MathematicsLearning, redirecting to auth");
      navigate('/auth');
    }
  }, [user, loading, navigate]);

  const handleStartAIQuestions = () => {
    console.log('🚀 STARTING AI QUESTIONS MODE');
    console.log('👤 Current user:', user?.id);
    setUseAIQuestions(true);
    setAiSessionKey(prev => {
      const newKey = prev + 1;
      console.log('🔑 New AI session key:', newKey);
      return newKey;
    });
  };

  // Show loading state while authentication is being checked
  if (loading) {
    console.log('⏳ Showing loading state - auth check in progress');
    return <div className="min-h-screen bg-gray-900 text-white flex items-center justify-center">
        <div className="text-center">
          <div className="text-4xl mb-4">🔢</div>
          <p className="text-lg">Loading your math lesson...</p>
        </div>
      </div>;
  }

  // Don't render the component if user is not authenticated
  if (!user) {
    console.log('❌ No user - component not rendering');
    return null;
  }

  console.log('🎯 Rendering main component with useAIQuestions:', useAIQuestions);

  // Show AI Questions Mode
  if (useAIQuestions) {
    console.log('🤖 Rendering AI Questions mode with session key:', aiSessionKey);
    return <div className="min-h-screen bg-gray-900 text-white">
        <LearningHeader />
        <div className="max-w-4xl mx-auto p-6">
          <Card className="bg-gradient-to-r from-green-900 to-blue-900 border-green-400 mb-6">
            <CardContent className="p-4 text-center">
              <Brain className="w-8 h-8 text-lime-400 mx-auto mb-2" />
              <p className="text-white">
                🤖 AI is generating a REAL personalized math question for fractions
              </p>
              <Button onClick={() => setUseAIQuestions(false)} variant="outline" className="mt-2 border-gray-600 text-slate-950 bg-slate-50">
                Back to Start
              </Button>
            </CardContent>
          </Card>
          
          <AILearningModule 
            key={aiSessionKey} 
            subject="matematik" 
            skillArea="fractions" 
            difficultyLevel={1}
            onBack={() => setUseAIQuestions(false)}
          />
        </div>
      </div>;
  }

  // Show initial start screen (no mode selection)
  return <div className="min-h-screen bg-gray-900 text-white">
      <LearningHeader />
      <div className="max-w-4xl mx-auto p-6">
        <Card className="bg-gray-800 border-gray-700 mb-6">
          <CardHeader>
            <CardTitle className="text-white text-center">AI Math Learning</CardTitle>
          </CardHeader>
          <CardContent className="text-center">
            <Card className="bg-gradient-to-r from-lime-900 to-green-900 border-lime-400">
              <CardContent className="p-6 text-center">
                <Brain className="w-12 h-12 text-lime-400 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-white mb-2">AI-Generated Math Questions</h3>
                <p className="text-lime-200 mb-4">
                  Get personalized math questions generated by AI based on your skill level
                </p>
                <Button onClick={handleStartAIQuestions} className="bg-lime-400 hover:bg-lime-500 text-black font-semibold">
                  <Brain className="w-4 h-4 mr-2" />
                  Start AI Math Questions
                </Button>
              </CardContent>
            </Card>
          </CardContent>
        </Card>
      </div>
    </div>;
};

export default MathematicsLearning;
