
import { Calculator, BookOpen, Microscope, Music, Monitor, Palette } from "lucide-react";

export const dailyActivities = [
  {
    id: 'mathematics',
    title: 'Mathematics',
    description: 'Arithmetic and problem solving with Nelie',
    icon: Calculator,
    duration: '20 min',
    level: 'Medium',
    color: 'from-blue-500 to-blue-600',
    aiEnhanced: true,
    subject: 'mathematics',
    skillArea: 'arithmetic',
    difficulty: 'Medium',
    status: 'available',
    progress: 0,
    estimatedTime: 20,
    nelieEnabled: true
  },
  {
    id: 'english',
    title: 'English',
    description: 'Reading comprehension and grammar with Nelie',
    icon: BookOpen,
    duration: '15 min',
    level: 'Easy',
    color: 'from-green-500 to-green-600',
    aiEnhanced: true,
    subject: 'english',
    skillArea: 'reading',
    difficulty: 'Easy',
    status: 'available',
    progress: 0,
    estimatedTime: 15,
    nelieEnabled: true
  },
  {
    id: 'science',
    title: 'Science',
    description: 'Natural sciences and experiments with Nelie',
    icon: Microscope,
    duration: '18 min',
    level: 'Medium',
    color: 'from-purple-500 to-purple-600',
    aiEnhanced: true,
    subject: 'science',
    skillArea: 'natural-sciences',
    difficulty: 'Medium',
    status: 'available',
    progress: 0,
    estimatedTime: 18,
    nelieEnabled: true
  },
  {
    id: 'music',
    title: 'Music',
    description: 'Musical theory and rhythm with Nelie',
    icon: Music,
    duration: '12 min',
    level: 'Easy',
    color: 'from-pink-500 to-pink-600',
    aiEnhanced: true,
    subject: 'music',
    skillArea: 'theory',
    difficulty: 'Easy',
    status: 'available',
    progress: 0,
    estimatedTime: 12,
    nelieEnabled: true
  },
  {
    id: 'computer-science',
    title: 'Computer Science',
    description: 'Programming concepts and logic with Nelie',
    icon: Monitor,
    duration: '25 min',
    level: 'Hard',
    color: 'from-orange-500 to-orange-600',
    aiEnhanced: true,
    subject: 'computer-science',
    skillArea: 'programming',
    difficulty: 'Hard',
    status: 'available',
    progress: 0,
    estimatedTime: 25,
    nelieEnabled: true
  },
  {
    id: 'creative',
    title: 'Creative Arts',
    description: 'Art, creativity and imagination with Nelie',
    icon: Palette,
    duration: '20 min',
    level: 'Easy',
    color: 'from-red-500 to-red-600',
    aiEnhanced: true,
    subject: 'creative-arts',
    skillArea: 'art',
    difficulty: 'Easy',
    status: 'available',
    progress: 0,
    estimatedTime: 20,
    nelieEnabled: true
  }
];
