
import { 
  Calculator, 
  BookOpen, 
  Microscope, 
  Monitor, 
  Palette, 
  Music, 
  Brain, 
  Globe, 
  Scroll, 
  Map, 
  Dumbbell, 
  Target 
} from "lucide-react";

export const dailyActivities = [
  {
    id: "mathematics",
    title: "Mathematics Mastery",
    description: "Advanced problem-solving with AI-powered adaptive learning paths. Master algebra, geometry, and statistics through personalized challenges.",
    icon: Calculator,
    duration: "45 min",
    level: "Adaptive",
    color: "bg-gradient-to-br from-orange-500 to-red-600",
    aiEnhanced: true,
    subject: "mathematics",
    skillArea: "general_mathematics"
  },
  {
    id: "math-fractions",
    title: "Fractions Practice",
    description: "Work on adding, subtracting, and comparing fractions.",
    icon: Calculator,
    duration: "30 min",
    level: "Adaptive",
    color: "bg-gradient-to-br from-orange-500 to-red-600",
    aiEnhanced: true,
    subject: "mathematics",
    skillArea: "fractions"
  },
  {
    id: "math-algebra",
    title: "Algebra Basics",
    description: "Solve equations and explore variables and expressions.",
    icon: Calculator,
    duration: "35 min",
    level: "Adaptive",
    color: "bg-gradient-to-br from-orange-500 to-red-600",
    aiEnhanced: true,
    subject: "mathematics",
    skillArea: "algebra"
  },
  {
    id: "english",
    title: "English Language Arts",
    description: "Develop exceptional reading, writing, and communication skills through immersive storytelling and creative expression projects.",
    icon: BookOpen,
    duration: "40 min",
    level: "Intermediate",
    color: "bg-gradient-to-br from-blue-500 to-indigo-600",
    aiEnhanced: true,
    subject: "english",
    skillArea: "general_english"
  },
  {
    id: "science",
    title: "Science & Technology",
    description: "Explore the wonders of science through virtual experiments, simulations, and hands-on discovery learning experiences.",
    icon: Microscope,
    duration: "50 min",
    level: "Advanced",
    color: "bg-gradient-to-br from-green-500 to-emerald-600",
    aiEnhanced: true,
    subject: "science",
    skillArea: "general_science"
  },
  {
    id: "computer-science",
    title: "Computer Science",
    description: "Learn programming, AI, and computational thinking through gamified coding challenges and real-world projects.",
    icon: Monitor,
    duration: "60 min",
    level: "Progressive",
    color: "bg-gradient-to-br from-yellow-500 to-orange-600",
    aiEnhanced: true,
    subject: "computer_science",
    skillArea: "programming_basics"
  },
  {
    id: "creative-arts",
    title: "Creative Arts & Design",
    description: "Express your creativity through digital art, music composition, and multimedia storytelling projects with AI guidance.",
    icon: Palette,
    duration: "45 min",
    level: "Creative",
    color: "bg-gradient-to-br from-pink-500 to-purple-600",
    aiEnhanced: true,
    subject: "creative_arts",
    skillArea: "general_creative_arts"
  },
  {
    id: "music",
    title: "Music Discovery",
    description: "Explore rhythm, melody, and composition through interactive music theory and digital instrument mastery sessions.",
    icon: Music,
    duration: "35 min",
    level: "Beginner",
    color: "bg-gradient-to-br from-purple-500 to-violet-600",
    aiEnhanced: true,
    subject: "music",
    skillArea: "music_theory"
  },
  {
    id: "mental-wellness",
    title: "Mental Wellness",
    description: "Learn about understanding emotions, developing healthy coping strategies, and building resilience for balanced living.",
    icon: Brain,
    duration: "30 min",
    level: "Essential",
    color: "bg-gradient-to-br from-green-500 to-teal-600",
    aiEnhanced: true,
    subject: "mental_wellness",
    skillArea: "general_mental_wellness"
  },
  {
    id: "language-lab",
    title: "Language Lab",
    description: "Interactive lessons for learning new languages with vocabulary building, grammar practice, and cultural insights.",
    icon: Globe,
    duration: "40 min",
    level: "Multi-level",
    color: "bg-gradient-to-br from-blue-500 to-cyan-600",
    aiEnhanced: true,
    subject: "language_lab",
    skillArea: "general_language_lab"
  },
  {
    id: "history-religion",
    title: "History & Religion",
    description: "Journey through world history, exploring pivotal events, influential figures, and the rich tapestry of global religions.",
    icon: Scroll,
    duration: "45 min",
    level: "Comprehensive",
    color: "bg-gradient-to-br from-orange-500 to-red-600",
    aiEnhanced: true,
    subject: "history_religion",
    skillArea: "general_history_religion"
  },
  {
    id: "geography",
    title: "Global Geography",
    description: "Explore Earth's diverse landscapes, climates, and the fascinating interplay between physical features and cultures.",
    icon: Map,
    duration: "40 min",
    level: "Exploratory",
    color: "bg-gradient-to-br from-cyan-500 to-blue-600",
    aiEnhanced: true,
    subject: "geography",
    skillArea: "general_geography"
  },
  {
    id: "body-lab",
    title: "BodyLab",
    description: "Interactive guide to healthy living through nutrition science, fitness principles, and holistic wellness practices.",
    icon: Dumbbell,
    duration: "35 min",
    level: "Active",
    color: "bg-gradient-to-br from-red-500 to-pink-600",
    aiEnhanced: true,
    subject: "body_lab",
    skillArea: "general_body_lab"
  },
  {
    id: "life-essentials",
    title: "Life Essentials",
    description: "Essential life skills including personal finance, household management, career development, and future planning.",
    icon: Target,
    duration: "50 min",
    level: "Practical",
    color: "bg-gradient-to-br from-purple-500 to-pink-600",
    aiEnhanced: true,
    subject: "life_essentials",
    skillArea: "general_life_essentials"
  }
];
