
// IMPORTANT (World History/Religions): All lesson content generated by this factory is currently placeholder.
// It requires thorough review, replacement, and approval by subject matter experts,
// instructional designers, and potentially cultural sensitivity reviewers before use.
// src/components/education/components/utils/EnhancedWorldHistoryReligionsLessonFactory.ts
import { EnhancedLessonConfig, ENHANCED_LESSON_PHASES } from './EnhancedLessonGenerator';
import { LessonActivity } from '../types/LessonTypes';

export const generateWorldHistoryReligionsLesson = (
  gradeLevel: number,
  learningStyle: 'mixed' | 'visual' | 'auditory' | 'kinesthetic' = 'mixed',
  sessionId: string = ''
): EnhancedLessonConfig => {
  const phases: LessonActivity[] = [
    {
      id: 'introduction',
      type: 'introduction',
      phase: 'introduction',
      title: 'Journey Through Time and Cultures',
      duration: ENHANCED_LESSON_PHASES.introduction.baseSeconds,
      phaseDescription: 'Engaging introduction to world history or religious studies concepts. // TODO: Replace with expert-reviewed World History/Religions content.',
      metadata: {
        subject: 'worldHistoryReligions',
        skillArea: 'culturalUnderstanding'
      },
      content: {
        hook: `Throughout history, people around the world have created amazing civilizations, told incredible stories, and developed ways of understanding life. Let's explore these fascinating cultures together! // TODO: Replace with expert-reviewed World History/Religions content. [Grade ${gradeLevel > 5 ? '6-12' : 'K-5'}: Adjust complexity of historical concepts.]`,
        thoughtQuestion: `// TODO (World History/Religions): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for World History/Religions: e.g., What can we learn from studying different cultures?]`
      },
    },
    {
      id: 'core-content',
      type: 'content-delivery',
      phase: 'content-delivery',
      title: 'Exploring Civilizations and Beliefs',
      duration: ENHANCED_LESSON_PHASES.contentDelivery.baseSeconds,
      phaseDescription: 'Core information about historical periods, civilizations, or world religions. // TODO: Replace with expert-reviewed World History/Religions content.',
      metadata: {
        subject: 'worldHistoryReligions',
        skillArea: 'culturalUnderstanding'
      },
      content: {
        concept: `Understanding [Topic: e.g., Ancient Civilizations, World Religions, Historical Timelines]. // TODO: Replace with expert-reviewed World History/Religions content. [Grade ${gradeLevel > 8 ? '9-12' : (gradeLevel > 5 ? '6-8' : 'K-5')}: Basic stories for younger, complex analysis for older.]`,
        explanation: `Key aspects of the historical period or cultural topic. // TODO: Replace with expert-reviewed World History/Religions content.`,
        thoughtQuestion: `// TODO (World History/Religions): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for World History/Religions: e.g., How did geography influence early civilizations?]`
      },
    },
    {
      id: 'interactive-activity',
      type: 'interactive-game',
      phase: 'interactive-game',
      title: 'Time Machine Explorer / Cultural Detective',
      duration: ENHANCED_LESSON_PHASES.interactiveGame.baseSeconds,
      phaseDescription: 'Interactive activity, e.g., virtual time travel, cultural artifact identification, historical timeline builder. // TODO: Replace with expert-reviewed World History/Religions content.',
      metadata: {
        subject: 'worldHistoryReligions',
        skillArea: 'culturalUnderstanding'
      },
      content: {
        gameType: 'exploration',
        activityInstructions: `// TODO (World History/Religions): Define a subject-specific interactive activity placeholder.
                     [Placeholder for World History/Religions: e.g., Interactive timeline or cultural comparison activity.]`,
      },
    },
    {
      id: 'application',
      type: 'application',
      phase: 'application',
      title: 'Cultural Bridge Builder / Historical Connections',
      duration: ENHANCED_LESSON_PHASES.application.baseSeconds,
      phaseDescription: 'Applying knowledge to understand connections between past and present or across cultures. // TODO: Replace with expert-reviewed World History/Religions content.',
      metadata: {
        subject: 'worldHistoryReligions',
        skillArea: 'culturalUnderstanding'
      },
      content: {
        scenario: `Think about how the historical period or culture we studied connects to our world today. What similarities and differences do you notice? // TODO: Replace with expert-reviewed World History/Religions content. [Grade ${gradeLevel > 8 ? '9-12' : '6-8'}: More complex analysis for older grades.]`,
        task: `Identify two connections between the past and present. // TODO: Replace with expert-reviewed World History/Religions content.`,
        thoughtQuestion: `// TODO (World History/Religions): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for World History/Religions: e.g., What traditions from the past do we still practice today?]`
      },
    },
    {
      id: 'creative-exploration',
      type: 'creative-exploration',
      phase: 'creative-exploration',
      title: 'Cultural Storyteller / Historical Museum',
      duration: ENHANCED_LESSON_PHASES.creativeExploration.baseSeconds,
      phaseDescription: 'Creative task, e.g., creating a historical story, designing a cultural celebration, or making a virtual museum exhibit. // TODO: Replace with expert-reviewed World History/Religions content.',
      metadata: {
        subject: 'worldHistoryReligions',
        skillArea: 'culturalUnderstanding'
      },
      content: {
        creativePrompt: `Create a story from the perspective of someone living in the historical period we studied, or design a respectful celebration that honors a cultural tradition. // TODO: Replace with expert-reviewed World History/Religions content.`,
        tools: ['Digital storytelling tool (simulated)', 'Timeline creator (simulated)'],
      },
    },
    {
      id: 'summary',
      type: 'summary',
      phase: 'summary',
      title: 'Celebrating Human Heritage',
      duration: ENHANCED_LESSON_PHASES.summary.baseSeconds,
      phaseDescription: 'Summarizing key insights about world history or cultural understanding. // TODO: Replace with expert-reviewed World History/Religions content.',
      metadata: {
        subject: 'worldHistoryReligions',
        skillArea: 'culturalUnderstanding'
      },
      content: {
        keyTakeaways: [
          `Key understanding of [Historical Concept or Cultural Practice]. // TODO: Replace with expert-reviewed World History/Religions content.`,
          `How studying history helps us understand each other. // TODO: Replace with expert-reviewed World History/Religions content.`,
        ],
        nextTopicSuggestion: `Next, we could explore [Specific Historical Period or Cultural Topic]. // TODO: Replace with expert-reviewed World History/Religions content.`
      },
    },
  ];

  return {
    subject: 'worldHistoryReligions',
    skillArea: 'culturalUnderstanding',
    gradeLevel,
    learningStyle: learningStyle,
    sessionId,
    title: `Placeholder World History/Religions Lesson (Grade ${gradeLevel})`,
    overview: 'This is a placeholder lesson exploring world history and cultural understanding, designed for various grade levels. // TODO: Replace with expert-reviewed World History/Religions content.',
    phases: phases,
    estimatedTotalDuration: phases.reduce((sum, phase) => sum + phase.duration, 0),
    learningObjectives: [
      `Understand [Specific Historical or Cultural Concept]. // TODO: Replace with expert-reviewed World History/Religions content.`,
      `Develop cultural awareness and respect. // TODO: Replace with expert-reviewed World History/Religions content.`
    ],
    materials: ['Device with internet access', 'Virtual timeline tools (simulated)'],
    assessmentMethods: ['Cultural comparison activities', 'Historical analysis', 'Creative projects'],
    keywords: ['History', 'Culture', 'Civilizations', 'Traditions', 'Heritage', 'Placeholder'],
  };
};
