
// IMPORTANT (Mental Wellness): All lesson content generated by this factory is currently placeholder.
// It requires thorough review, replacement, and approval by subject matter experts,
// instructional designers, and potentially cultural sensitivity reviewers before use.
// src/components/education/components/utils/EnhancedMentalWellnessLessonFactory.ts
import { EnhancedLessonConfig, ENHANCED_LESSON_PHASES } from './EnhancedLessonGenerator';
import { LessonActivity } from '../types/LessonTypes';

export const generateMentalWellnessLesson = (
  gradeLevel: number,
  learningStyle: 'mixed' | 'visual' | 'auditory' | 'kinesthetic' = 'mixed',
  sessionId: string = ''
): EnhancedLessonConfig => {
  const gradeRange = gradeLevel > 8 ? '9-12' : (gradeLevel > 5 ? '6-8' : 'K-5');
  
  const phases: LessonActivity[] = [
    {
      id: 'introduction',
      type: 'introduction',
      phase: 'introduction',
      title: 'Welcome to Your Mental Wellness Journey',
      duration: ENHANCED_LESSON_PHASES.introduction.baseSeconds,
      phaseDescription: 'Introduction to mental wellness concepts in an age-appropriate way. // TODO: Replace with expert-reviewed Mental Wellness content.',
      metadata: {
        subject: 'mentalWellness',
        skillArea: 'emotionalHealth'
      },
      content: {
        hook: `Have you ever noticed how some days you feel really happy and energetic, while other days you might feel a bit down or worried? Today we're going to learn about taking care of our minds and feelings! // TODO: Replace with expert-reviewed Mental Wellness content. [Grade ${gradeRange}: Adjust language and concepts appropriately.]`,
        thoughtQuestion: `// TODO (Mental Wellness): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Mental Wellness: e.g., What makes you feel calm and happy?]`
      },
    },
    {
      id: 'core-content',
      type: 'content-delivery',
      phase: 'content-delivery',
      title: 'Understanding Your Mind & Emotions',
      duration: ENHANCED_LESSON_PHASES.contentDelivery.baseSeconds,
      phaseDescription: 'Core information about emotional regulation, stress management, and positive mental health habits. // TODO: Replace with expert-reviewed Mental Wellness content.',
      metadata: {
        subject: 'mentalWellness',
        skillArea: 'emotionalHealth'
      },
      content: {
        concept: `Understanding [Topic: e.g., Emotions, Stress Response, Coping Strategies]. // TODO: Replace with expert-reviewed Mental Wellness content. [Grade ${gradeRange}: Simple emotion names for younger, complex emotional regulation for older.]`,
        explanation: `Key principles of mental wellness and emotional health. // TODO: Replace with expert-reviewed Mental Wellness content.`,
        segments: [
          {
            title: 'Understanding Emotions',
            concept: 'Basic emotional awareness concepts. // TODO: Replace with expert-reviewed Mental Wellness content.',
            explanation: 'How emotions work and why they're important. // TODO: Replace with expert-reviewed Mental Wellness content.'
          }
        ],
        thoughtQuestion: `// TODO (Mental Wellness): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Mental Wellness: e.g., Why is it important to talk about our feelings?]`
      },
    },
    {
      id: 'interactive-activity',
      type: 'interactive-game',
      phase: 'interactive-game',
      title: 'Emotion Detective / Mindfulness Game',
      duration: ENHANCED_LESSON_PHASES.interactiveGame.baseSeconds,
      phaseDescription: 'Interactive activity, e.g., "Emotion Detector" game, guided breathing exercise, "Positive Thoughts" challenge. // TODO: Replace with expert-reviewed Mental Wellness content.',
      metadata: {
        subject: 'mentalWellness',
        skillArea: 'emotionalHealth'
      },
      content: {
        gameType: 'mindfulness-practice', // Example
        activityInstructions: `// TODO (Mental Wellness): Define a subject-specific interactive activity placeholder.
                     [Placeholder for Mental Wellness: e.g., A simple breathing exercise or emotion identification game.]`,
      },
    },
    {
      id: 'application',
      type: 'application',
      phase: 'application',
      title: 'My Wellness Toolkit / Calm Space',
      duration: ENHANCED_LESSON_PHASES.application.baseSeconds,
      phaseDescription: 'Applying knowledge to create personal coping strategies or a calming routine. // TODO: Replace with expert-reviewed Mental Wellness content.',
      metadata: {
        subject: 'mentalWellness',
        skillArea: 'emotionalHealth'
      },
      content: {
        scenario: `Think about a time when you felt worried or upset. What helped you feel better? Let's create your personal "calm down" toolkit with strategies that work for you. // TODO: Replace with expert-reviewed Mental Wellness content. [Grade ${gradeLevel > 8 ? '9-12' : '6-8'}: More sophisticated coping strategies for older students.]`,
        task: `Choose 3 strategies that help you feel calm and happy. // TODO: Replace with expert-reviewed Mental Wellness content.`,
        thoughtQuestion: `// TODO (Mental Wellness): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Mental Wellness: e.g., Who are the people you can talk to when you're feeling sad?]`
      },
    },
    {
      id: 'creative-exploration',
      type: 'creative-exploration',
      phase: 'creative-exploration',
      title: 'Gratitude Art / Positive Affirmations Creator',
      duration: ENHANCED_LESSON_PHASES.creativeExploration.baseSeconds,
      phaseDescription: 'Creative task, e.g., creating a gratitude journal page, drawing feelings, or making positive affirmation cards. // TODO: Replace with expert-reviewed Mental Wellness content.',
      metadata: {
        subject: 'mentalWellness',
        skillArea: 'emotionalHealth'
      },
      content: {
        creativePrompt: `Create a "gratitude artwork" showing three things you're thankful for, or design positive affirmation cards to remind yourself how awesome you are! // TODO: Replace with expert-reviewed Mental Wellness content.`,
        tools: ['Digital drawing tool (simulated)', 'Text editor', 'Mood tracking template (simulated)'],
      },
    },
    {
      id: 'summary',
      type: 'summary',
      phase: 'summary',
      title: 'Your Mental Wellness Journey Continues',
      duration: ENHANCED_LESSON_PHASES.summary.baseSeconds,
      phaseDescription: 'Summarizing key takeaways for mental wellness and emotional health. // TODO: Replace with expert-reviewed Mental Wellness content.',
      metadata: {
        subject: 'mentalWellness',
        skillArea: 'emotionalHealth'
      },
      content: {
        keyTakeaways: [
          `The importance of [Emotional Awareness Concept]. // TODO: Replace with expert-reviewed Mental Wellness content.`,
          `How [Coping Strategy] helps manage stress. // TODO: Replace with expert-reviewed Mental Wellness content.`,
          `Why [Self-Care Practice] is important. // TODO: Replace with expert-reviewed Mental Wellness content.`,
        ],
        nextTopicSuggestion: `Next, we could explore [Specific Mental Health Topic or Coping Technique]. // TODO: Replace with expert-reviewed Mental Wellness content.`
      },
    },
  ];

  return {
    subject: 'mentalWellness',
    skillArea: 'emotionalHealth',
    gradeLevel,
    learningStyle: learningStyle,
    sessionId,
    title: `Placeholder Mental Wellness: Emotional Health Lesson (Grade ${gradeLevel})`,
    overview: 'This is a placeholder lesson exploring mental wellness and emotional health, designed for various grade levels. // TODO: Replace with expert-reviewed Mental Wellness content.',
    phases: phases,
    estimatedTotalDuration: phases.reduce((sum, phase) => sum + phase.duration, 0),
    learningObjectives: [
      `Understand the basics of [Specific Emotional Health Topic]. // TODO: Replace with expert-reviewed Mental Wellness content.`,
      `Learn effective [Specific Coping Strategy]. // TODO: Replace with expert-reviewed Mental Wellness content.`,
      `Practice [Specific Mindfulness Technique]. // TODO: Replace with expert-reviewed Mental Wellness content.`
    ],
    materials: ['Device with internet access', 'Optional: journal, art supplies (simulated for activities)'],
    assessmentMethods: ['Self-reflection activities', 'Participation in mindfulness exercises', 'Coping strategy development'],
    keywords: ['Mental Health', 'Emotions', 'Wellness', 'Mindfulness', 'Coping', 'Self-Care', 'Placeholder'],
  };
};
