// IMPORTANT (Global Geography): All lesson content generated by this factory is currently placeholder.
// It requires thorough review, replacement, and approval by subject matter experts,
// instructional designers, and potentially cultural sensitivity reviewers before use.
// src/components/education/components/utils/EnhancedGlobalGeographyLessonFactory.ts
import { EnhancedLessonConfig, ENHANCED_LESSON_PHASES } from './EnhancedLessonGenerator';
import { LessonActivity } from '../types/LessonTypes';

export const generateGlobalGeographyLesson = (
  gradeLevel: number,
  learningStyle: string = 'mixed',
  sessionId: string = ''
): EnhancedLessonConfig => {
  const phases: LessonActivity[] = [
    {
      id: 'introduction',
      type: 'introduction',
      phase: 'introduction',
      title: 'Our Amazing Planet Awaits!',
      duration: ENHANCED_LESSON_PHASES.introduction.baseSeconds,
      phaseDescription: 'Engaging introduction to a geographical concept or region. // TODO: Replace with expert-reviewed Global Geography content.',
      content: {
        hook: `Imagine you're an explorer setting foot on a new continent! What wonders would you expect to find? // TODO: Replace with expert-reviewed Global Geography content. [Grade ${gradeLevel > 5 ? '6-12' : 'K-5'}: Adjust complexity of exploration idea.]`,
        thoughtQuestion: `// TODO (Global Geography): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Global Geography: e.g., Why are rainforests important for the planet?]`
      },
    },
    {
      id: 'core-content',
      type: 'content-delivery',
      phase: 'content-delivery',
      title: 'Mapping Our World',
      duration: ENHANCED_LESSON_PHASES.contentDelivery.baseSeconds,
      phaseDescription: 'Delivering core information about physical landscapes, climate zones, or human-environment interaction. // TODO: Replace with expert-reviewed Global Geography content.',
      content: {
        concept: `Understanding [Geographic Feature, e.g., Climate Zones, Mountain Ranges, River Systems]. // TODO: Replace with expert-reviewed Global Geography content. [Grade ${gradeLevel > 8 ? '9-12' : (gradeLevel > 5 ? '6-8' : 'K-5')}: Tailor depth, e.g., basic landforms for younger, complex climate patterns for older.]`,
        explanation: `Key characteristics and importance of [Topic]. // TODO: Replace with expert-reviewed Global Geography content.`,
        thoughtQuestion: `// TODO (Global Geography): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Global Geography: e.g., How do mountains affect weather patterns?]`
      },
    },
    {
      id: 'interactive-activity',
      type: 'interactive-game',
      phase: 'interactive-game',
      title: 'Geo Detective: Landform ID / Climate Match',
      duration: ENHANCED_LESSON_PHASES.interactiveGame.baseSeconds,
      phaseDescription: 'Interactive activity, e.g., identifying landforms from images, matching animals to climate zones, virtual map quiz. // TODO: Replace with expert-reviewed Global Geography content.',
      content: {
        gameType: 'matching', // Example
        activityInstructions: `// TODO (Global Geography): Define a subject-specific interactive activity placeholder.
                     [Placeholder for Global Geography: e.g., Interactive map quiz to identify continents and oceans.]`,
      },
    },
    {
      id: 'application',
      type: 'application',
      phase: 'application',
      title: 'Geography in Action: Sustainable City / Trip Planning',
      duration: ENHANCED_LESSON_PHASES.application.baseSeconds,
      phaseDescription: 'Applying geographical knowledge to real-world scenarios, e.g., planning a sustainable city or an eco-friendly trip. // TODO: Replace with expert-reviewed Global Geography content.',
      content: {
        scenario: `Imagine you need to plan a new city. What geographical factors would you consider for sustainability and growth? // TODO: Replace with expert-reviewed Global Geography content. [Grade ${gradeLevel > 8 ? '9-12' : '6-8'}: Younger grades might plan a local park or community garden.]`,
        task: `List three key geographical considerations for your plan. // TODO: Replace with expert-reviewed Global Geography content.`,
        thoughtQuestion: `// TODO (Global Geography): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Global Geography: e.g., How can understanding population density help plan city services?]`
      },
    },
    {
      id: 'creative-exploration',
      type: 'creative-exploration',
      phase: 'creative-exploration',
      title: 'Design Your Own Island / Travel Blogger',
      duration: ENHANCED_LESSON_PHASES.creativeExploration.baseSeconds,
      phaseDescription: 'Creative task, e.g., designing an imaginary island with specific geographical features, or writing a travel blog about a chosen country. // TODO: Replace with expert-reviewed Global Geography content.',
      content: {
        creativePrompt: `Design your own island, including its climate, landforms, and potential resources. Or, write a short travel blog entry about a country you find fascinating. // TODO: Replace with expert-reviewed Global Geography content.`,
        tools: ['Digital drawing tool (simulated)', 'Text editor'],
      },
    },
    {
      id: 'summary',
      type: 'summary',
      phase: 'summary',
      title: 'Our Interconnected World',
      duration: ENHANCED_LESSON_PHASES.summary.baseSeconds,
      phaseDescription: 'Summarizing key geographical concepts and their importance. // TODO: Replace with expert-reviewed Global Geography content.',
      content: {
        keyTakeaways: [
          `Key understanding of [Geographic Concept, e.g., Earth's layers, climate's impact]. // TODO: Replace with expert-reviewed Global Geography content.`,
          `How geography shapes human life and societies. // TODO: Replace with expert-reviewed Global Geography content.`,
        ],
        nextTopicSuggestion: `Next, we could explore [Specific Region or Geographic Phenomenon]. // TODO: Replace with expert-reviewed Global Geography content.`
      },
    },
  ];

  return {
    subject: 'globalGeography',
    skillArea: 'foundations',
    gradeLevel,
    learningStyle: learningStyle,
    sessionId,
    title: `Placeholder Global Geography Lesson (Grade ${gradeLevel})`,
    overview: 'This is a placeholder lesson exploring global geography, designed to be adapted for various grade levels. // TODO: Replace with expert-reviewed Global Geography content.',
    phases: phases,
    estimatedTotalDuration: phases.reduce((sum, phase) => sum + phase.duration, 0),
    learningObjectives: [
      `Understand [Specific Geographic Concept]. // TODO: Replace with expert-reviewed Global Geography content.`,
      `Analyze the relationship between humans and their environment. // TODO: Replace with expert-reviewed Global Geography content.`
    ],
    materials: ['Device with internet access', 'Interactive maps (simulated)'],
    assessmentMethods: ['Map quizzes', 'Scenario analysis', 'Creative projects'],
    keywords: ['Geography', 'Planet', 'Maps', 'Climate', 'Environment', 'Placeholder'],
  };
};
