
// IMPORTANT (BodyLab): All lesson content generated by this factory is currently placeholder.
// It requires thorough review, replacement, and approval by subject matter experts,
// instructional designers, and potentially cultural sensitivity reviewers before use.
// src/components/education/components/utils/EnhancedBodyLabLessonFactory.ts
import { EnhancedLessonConfig, ENHANCED_LESSON_PHASES } from './EnhancedLessonGenerator';
import { LessonActivity } from '../types/LessonTypes';

export const generateBodyLabLesson = (
  gradeLevel: number,
  learningStyle: 'mixed' | 'visual' | 'auditory' | 'kinesthetic' = 'mixed',
  sessionId: string = ''
): EnhancedLessonConfig => {
  const phases: LessonActivity[] = [
    {
      id: 'introduction',
      type: 'introduction',
      phase: 'introduction',
      title: 'Energize Your Life!',
      duration: ENHANCED_LESSON_PHASES.introduction.baseSeconds,
      phaseDescription: 'Engaging introduction to healthy living concepts. // TODO: Replace with expert-reviewed BodyLab content.',
      metadata: {
        subject: 'bodyLab',
        skillArea: 'holisticHealth'
      },
      content: {
        hook: `How does your body feel when you're full of energy versus when you're tired? Let's explore how to feel our best! // TODO: Replace with expert-reviewed BodyLab content. [Grade ${gradeLevel > 5 ? '6-12' : 'K-5'}: Use simpler language for younger grades.]`,
        thoughtQuestion: `// TODO (BodyLab): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for BodyLab: e.g., Why is drinking water important for your body?]`
      },
    },
    {
      id: 'core-content',
      type: 'content-delivery',
      phase: 'content-delivery',
      title: 'Fueling & Moving Your Amazing Body',
      duration: ENHANCED_LESSON_PHASES.contentDelivery.baseSeconds,
      phaseDescription: 'Delivering core information about nutrition, physical fitness, and mental well-being. // TODO: Replace with expert-reviewed BodyLab content.',
      metadata: {
        subject: 'bodyLab',
        skillArea: 'holisticHealth'
      },
      content: {
        concept: `Understanding [Topic: e.g., Food Groups, Benefits of Exercise, Mindfulness Basics]. // TODO: Replace with expert-reviewed BodyLab content. [Grade ${gradeLevel > 8 ? '9-12' : (gradeLevel > 5 ? '6-8' : 'K-5')}: Tailor depth, e.g., simple food groups for K-2, macronutrients for 9-12, types of exercise, stress reduction techniques.]`,
        explanation: `Key principles and benefits of [Topic]. // TODO: Replace with expert-reviewed BodyLab content.`,
        thoughtQuestion: `// TODO (BodyLab): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for BodyLab: e.g., What are two benefits of regular exercise?]`
      },
    },
    {
      id: 'interactive-activity',
      type: 'interactive-game',
      phase: 'interactive-game',
      title: 'Healthy Choices Challenge / Fitness Fun',
      duration: ENHANCED_LESSON_PHASES.interactiveGame.baseSeconds,
      phaseDescription: 'Interactive activity, e.g., "Meal Maker" game, virtual fitness challenge, "Stress Buster" scenario game. // TODO: Replace with expert-reviewed BodyLab content.',
      metadata: {
        subject: 'bodyLab',
        skillArea: 'holisticHealth'
      },
      content: {
        gameType: 'problem-solving', // Example
        activityInstructions: `// TODO (BodyLab): Define a subject-specific interactive activity placeholder.
                     [Placeholder for BodyLab: e.g., A drag-and-drop game to build a balanced meal from different food groups.]`,
      },
    },
    {
      id: 'application',
      type: 'application',
      phase: 'application',
      title: 'My Healthy Day / Wellness Plan',
      duration: ENHANCED_LESSON_PHASES.application.baseSeconds,
      phaseDescription: 'Applying knowledge to create a personal healthy habit or plan. // TODO: Replace with expert-reviewed BodyLab content.',
      metadata: {
        subject: 'bodyLab',
        skillArea: 'holisticHealth'
      },
      content: {
        scenario: `Plan a healthy meal for your family, or design a 15-minute fun workout routine you can do at home. How can you incorporate a mindfulness moment into your day? // TODO: Replace with expert-reviewed BodyLab content. [Grade ${gradeLevel > 8 ? '9-12' : '6-8'}: More complex planning for older grades.]`,
        task: `Outline your meal, workout, or mindfulness strategy. // TODO: Replace with expert-reviewed BodyLab content.`,
        thoughtQuestion: `// TODO (BodyLab): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for BodyLab: e.g., What is one challenge you might face when trying to eat healthy, and how could you overcome it?]`
      },
    },
    {
      id: 'creative-exploration',
      type: 'creative-exploration',
      phase: 'creative-exploration',
      title: 'Wellness Poster / Healthy Recipe Creator',
      duration: ENHANCED_LESSON_PHASES.creativeExploration.baseSeconds,
      phaseDescription: 'Creative task, e.g., designing a wellness campaign poster, creating a new healthy recipe, or making a short video about your favorite exercise. // TODO: Replace with expert-reviewed BodyLab content.',
      metadata: {
        subject: 'bodyLab',
        skillArea: 'holisticHealth'
      },
      content: {
        creativePrompt: `Design a poster promoting a healthy habit, or invent a new healthy snack recipe and describe it. // TODO: Replace with expert-reviewed BodyLab content.`,
        tools: ['Digital drawing tool (simulated)', 'Text editor', 'Recipe card template (simulated)'],
      },
    },
    {
      id: 'summary',
      type: 'summary',
      phase: 'summary',
      title: 'Your Path to a Healthier You!',
      duration: ENHANCED_LESSON_PHASES.summary.baseSeconds,
      phaseDescription: 'Summarizing key takeaways for healthy living. // TODO: Replace with expert-reviewed BodyLab content.',
      metadata: {
        subject: 'bodyLab',
        skillArea: 'holisticHealth'
      },
      content: {
        keyTakeaways: [
          `The importance of [Nutrition Concept]. // TODO: Replace with expert-reviewed BodyLab content.`,
          `Benefits of [Fitness Principle]. // TODO: Replace with expert-reviewed BodyLab content.`,
          `How [Mental Wellness Practice] helps. // TODO: Replace with expert-reviewed BodyLab content.`,
        ],
        nextTopicSuggestion: `Next, we could explore [Specific Diet, Exercise Type, or Stress Management Technique]. // TODO: Replace with expert-reviewed BodyLab content.`
      },
    },
  ];

  return {
    subject: 'bodyLab',
    skillArea: 'holisticHealth',
    gradeLevel,
    learningStyle: learningStyle,
    sessionId,
    title: `Placeholder BodyLab: Healthy Living Lesson (Grade ${gradeLevel})`,
    overview: 'This is a placeholder lesson exploring nutrition, fitness, and mental well-being, designed for various grade levels. // TODO: Replace with expert-reviewed BodyLab content.',
    phases: phases,
    estimatedTotalDuration: phases.reduce((sum, phase) => sum + phase.duration, 0),
    learningObjectives: [
      `Understand the basics of [Specific Nutrition Topic]. // TODO: Replace with expert-reviewed BodyLab content.`,
      `Learn about effective [Specific Fitness Topic]. // TODO: Replace with expert-reviewed BodyLab content.`,
      `Practice [Specific Mental Wellness Technique]. // TODO: Replace with expert-reviewed BodyLab content.`
    ],
    materials: ['Device with internet access', 'Optional: yoga mat, water bottle (simulated for activities)'],
    assessmentMethods: ['Quizzes', 'Activity participation', 'Plan creation'],
    keywords: ['Health', 'Fitness', 'Nutrition', 'Wellness', 'Exercise', 'Mindfulness', 'Placeholder'],
  };
};
