
// IMPORTANT (Life Essentials): All lesson content generated by this factory is currently placeholder.
// It requires thorough review, replacement, and approval by subject matter experts,
// instructional designers, and potentially cultural sensitivity reviewers before use.
// src/components/education/components/utils/EnhancedLifeEssentialsLessonFactory.ts
import { EnhancedLessonConfig, ENHANCED_LESSON_PHASES } from './EnhancedLessonGenerator';
import { LessonActivity } from '../types/LessonTypes';

export const generateLifeEssentialsLesson = (
  gradeLevel: number, // Likely targeting grades 9-12 mostly
  learningStyle: 'mixed' | 'visual' | 'auditory' | 'kinesthetic' = 'mixed',
  sessionId: string = ''
): EnhancedLessonConfig => {
  const phases: LessonActivity[] = [
    {
      id: 'introduction',
      type: 'introduction',
      phase: 'introduction',
      title: 'Building Your Future: Skills for Success',
      duration: ENHANCED_LESSON_PHASES.introduction.baseSeconds,
      phaseDescription: 'Engaging introduction to a key life skill. // TODO: Replace with expert-reviewed Life Essentials content.',
      metadata: {
        subject: 'lifeEssentials',
        skillArea: 'practicalSkills'
      },
      content: {
        hook: `Imagine you've just received your first paycheck or are looking for your first apartment. What are the first things you need to consider? // TODO: Replace with expert-reviewed Life Essentials content. [Target Grade: ${gradeLevel > 8 ? '9-12' : 'Middle School if applicable'}]`,
        thoughtQuestion: `// TODO (Life Essentials): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Life Essentials: e.g., Why is having a budget important?]`
      },
    },
    {
      id: 'core-content',
      type: 'content-delivery',
      phase: 'content-delivery',
      title: 'Mastering Real-World Challenges',
      duration: ENHANCED_LESSON_PHASES.contentDelivery.baseSeconds,
      phaseDescription: 'Delivering core information on personal finance, household management, career planning, etc. // TODO: Replace with expert-reviewed Life Essentials content.',
      metadata: {
        subject: 'lifeEssentials',
        skillArea: 'practicalSkills'
      },
      content: {
        concept: `Understanding [Topic: e.g., Budgeting, Understanding Credit, Renting vs Buying, Job Applications, Basic Taxes]. // TODO: Replace with expert-reviewed Life Essentials content. [Target Grade: ${gradeLevel > 8 ? '9-12' : 'Middle School for simpler concepts like basic saving'}]`,
        explanation: `Key principles, steps, and importance of [Topic]. // TODO: Replace with expert-reviewed Life Essentials content.`,
        thoughtQuestion: `// TODO (Life Essentials): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Life Essentials: e.g., What are two advantages of understanding your credit score?]`
      },
    },
    {
      id: 'interactive-activity',
      type: 'interactive-game',
      phase: 'interactive-game',
      title: 'Budget Boss / Career Pathfinder / Lease Detective',
      duration: ENHANCED_LESSON_PHASES.interactiveGame.baseSeconds,
      phaseDescription: 'Interactive scenario or tool, e.g., creating a mock budget, evaluating job offers, analyzing a sample lease agreement. // TODO: Replace with expert-reviewed Life Essentials content.',
      metadata: {
        subject: 'lifeEssentials',
        skillArea: 'practicalSkills'
      },
      content: {
        gameType: 'simulation', // Example
        activityInstructions: `// TODO (Life Essentials): Define a subject-specific interactive activity placeholder.
                     [Placeholder for Life Essentials: e.g., A budgeting game where you manage income and expenses for a month.]`,
      },
    },
    {
      id: 'application',
      type: 'application',
      phase: 'application',
      title: 'My Financial Goal / Future Career Plan',
      duration: ENHANCED_LESSON_PHASES.application.baseSeconds,
      phaseDescription: 'Applying knowledge to create a personal financial goal, research a career path, or draft a basic household plan. // TODO: Replace with expert-reviewed Life Essentials content.',
      metadata: {
        subject: 'lifeEssentials',
        skillArea: 'practicalSkills'
      },
      content: {
        scenario: `Set a realistic financial goal for the next year (e.g., saving for a car, a trip, or an emergency fund) and outline the steps to achieve it. Or, research the educational requirements and average salary for a career you're interested in. // TODO: Replace with expert-reviewed Life Essentials content. [Target Grade: 9-12]`,
        task: `Document your goal and steps, or summarize your career research findings. // TODO: Replace with expert-reviewed Life Essentials content.`,
        thoughtQuestion: `// TODO (Life Essentials): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for Life Essentials: e.g., What are three important factors to consider when choosing a career path?]`
      },
    },
    {
      id: 'creative-exploration',
      type: 'creative-exploration',
      phase: 'creative-exploration',
      title: 'Dream Board for Adulting / "How To" Guide',
      duration: ENHANCED_LESSON_PHASES.creativeExploration.baseSeconds,
      phaseDescription: 'Creative task, e.g., creating a vision board for future life goals, or developing a simple "how-to" guide for a practical skill (e.g., how to read a utility bill, how to prepare for an interview). // TODO: Replace with expert-reviewed Life Essentials content.',
      metadata: {
        subject: 'lifeEssentials',
        skillArea: 'practicalSkills'
      },
      content: {
        creativePrompt: `Create a digital vision board for your goals in the next 5 years (career, housing, personal development). Or, write a simple guide explaining [a practical skill like understanding an apartment lease]. // TODO: Replace with expert-reviewed Life Essentials content. [Target Grade: 9-12]`,
        tools: ['Digital collage tool (simulated)', 'Text editor/presentation software (simulated)'],
      },
    },
    {
      id: 'summary',
      type: 'summary',
      phase: 'summary',
      title: 'Equipped for the Future',
      duration: ENHANCED_LESSON_PHASES.summary.baseSeconds,
      phaseDescription: 'Summarizing key life skills and resources. // TODO: Replace with expert-reviewed Life Essentials content.',
      metadata: {
        subject: 'lifeEssentials',
        skillArea: 'practicalSkills'
      },
      content: {
        keyTakeaways: [
          `Key principle of [Financial Literacy Concept]. // TODO: Replace with expert-reviewed Life Essentials content.`,
          `Importance of [Career Planning Step / Household Skill]. // TODO: Replace with expert-reviewed Life Essentials content.`,
        ],
        nextTopicSuggestion: `Next, we could delve deeper into [Specific Investment Type, Advanced Career Strategies, or Home Maintenance]. // TODO: Replace with expert-reviewed Life Essentials content.`
      },
    },
  ];

  return {
    subject: 'lifeEssentials',
    skillArea: 'practicalSkills',
    gradeLevel,
    learningStyle: learningStyle,
    sessionId,
    title: `Placeholder Life Essentials Lesson (Grade ${gradeLevel})`,
    overview: 'This is a placeholder lesson covering practical skills for navigating adulthood, primarily aimed at high school students. // TODO: Replace with expert-reviewed Life Essentials content.',
    phases: phases,
    estimatedTotalDuration: phases.reduce((sum, phase) => sum + phase.duration, 0),
    learningObjectives: [
      `Understand key concepts in [Specific Personal Finance Topic, e.g., budgeting]. // TODO: Replace with expert-reviewed Life Essentials content.`,
      `Develop strategies for [Specific Career/Household Topic, e.g., job searching]. // TODO: Replace with expert-reviewed Life Essentials content.`
    ],
    materials: ['Device with internet access', 'Simulated financial tools/documents'],
    assessmentMethods: ['Scenario analysis', 'Budget creation', 'Goal setting exercises'],
    keywords: ['Life Skills', 'Personal Finance', 'Career', 'Budgeting', 'Adulthood', 'Placeholder'],
  };
};
