// IMPORTANT (World History & Global Religions): All lesson content generated by this factory is currently placeholder.
// It requires thorough review, replacement, and approval by subject matter experts,
// instructional designers, and potentially cultural sensitivity reviewers before use.
// src/components/education/components/utils/EnhancedWorldHistoryReligionsLessonFactory.ts
import { EnhancedLessonConfig, ENHANCED_LESSON_PHASES } from './EnhancedLessonGenerator';
import { LessonActivity } from '../types/LessonTypes';

export const generateWorldHistoryReligionsLesson = (
  gradeLevel: number,
  learningStyle: string = 'mixed',
  sessionId: string = ''
): EnhancedLessonConfig => {
  const phases: LessonActivity[] = [
    {
      id: 'introduction',
      type: 'introduction',
      phase: 'introduction',
      title: 'Echoes of the Past, Voices of Belief',
      duration: ENHANCED_LESSON_PHASES.introduction.baseSeconds,
      phaseDescription: 'Engaging introduction to a historical period or religious concept. // TODO: Replace with expert-reviewed World History & Religions content.',
      content: {
        hook: `Imagine discovering an ancient artifact... What stories could it tell? // TODO: Replace with expert-reviewed World History & Religions content. [Grade ${gradeLevel > 5 ? '6-12' : 'K-5'}: Adjust complexity of artifact/story]`,
        thoughtQuestion: `// TODO (World History & Global Religions): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for World History & Global Religions: e.g., What might have been a daily challenge for someone living in Ancient Rome?]`
      },
    },
    {
      id: 'core-content',
      type: 'content-delivery',
      phase: 'content-delivery',
      title: 'Journey Through Time & Faith',
      duration: ENHANCED_LESSON_PHASES.contentDelivery.baseSeconds,
      phaseDescription: 'Delivering core information about a specific civilization, historical event, or religious tradition. // TODO: Replace with expert-reviewed World History & Religions content.',
      content: {
        concept: `Exploring Ancient [Civilization Name] or [Religious Tradition]. // TODO: Replace with expert-reviewed World History & Religions content. [Grade ${gradeLevel > 8 ? '9-12' : (gradeLevel > 5 ? '6-8' : 'K-5')}: Tailor depth of content, e.g., focus on daily life for younger grades, socio-political structures for older.]`,
        explanation: `Key facts, figures, and narratives about [Topic]. // TODO: Replace with expert-reviewed World History & Religions content.`,
        thoughtQuestion: `// TODO (World History & Global Religions): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for World History & Global Religions: e.g., How did the geography of Egypt influence its development?]`
      },
    },
    {
      id: 'interactive-activity',
      type: 'interactive-game',
      phase: 'interactive-game',
      title: 'Historical Detective / Symbols of Faith',
      duration: ENHANCED_LESSON_PHASES.interactiveGame.baseSeconds,
      phaseDescription: 'Interactive activity to reinforce learning, e.g., matching game, timeline sort, virtual dig. // TODO: Replace with expert-reviewed World History & Religions content.',
      content: {
        gameType: 'matching', // Example
        activityInstructions: `// TODO (World History & Global Religions): Define a subject-specific interactive activity placeholder.
                     [Placeholder for World History & Global Religions: e.g., Interactive timeline for the Roman Empire, or a quiz matching religious symbols to their faiths.]`,
        // options, correctAnswer etc. would be populated by actual game logic
      },
    },
    {
      id: 'application',
      type: 'application',
      phase: 'application',
      title: 'Connecting Past to Present / Understanding Beliefs',
      duration: ENHANCED_LESSON_PHASES.application.baseSeconds,
      phaseDescription: 'Applying historical understanding to current events or analyzing the impact of religious beliefs on society. // TODO: Replace with expert-reviewed World History & Religions content.',
      content: {
        scenario: `Consider how [Historical Event/Religious Concept] influences [Modern Situation/Ethical Dilemma]. // TODO: Replace with expert-reviewed World History & Religions content. [Grade ${gradeLevel > 8 ? '9-12' : '6-8'}: Younger grades might compare past and present daily life.]`,
        task: `Write a short paragraph or discuss your thoughts. // TODO: Replace with expert-reviewed World History & Religions content.`,
        thoughtQuestion: `// TODO (World History & Global Religions): Add placeholder for a comprehension/thought question.
                     This will eventually be powered by useUnifiedQuestionGeneration.
                     [Placeholder for World History & Global Religions: e.g., How can understanding past conflicts help us prevent future ones?]`
      },
    },
    {
      id: 'creative-exploration',
      type: 'creative-exploration',
      phase: 'creative-exploration',
      title: 'Museum Curator / Storyteller of Traditions',
      duration: ENHANCED_LESSON_PHASES.creativeExploration.baseSeconds,
      phaseDescription: 'Creative task, e.g., designing a virtual museum exhibit, writing a historical fiction piece, or creating a presentation on a religious festival. // TODO: Replace with expert-reviewed World History & Religions content.',
      content: {
        creativePrompt: `Design an exhibit for a museum about [Topic] or write a short story from the perspective of someone living in [Historical Period/Religious Community]. // TODO: Replace with expert-reviewed World History & Religions content.`,
        tools: ['Digital drawing tool (simulated)', 'Text editor'],
      },
    },
    {
      id: 'summary',
      type: 'summary',
      phase: 'summary',
      title: 'Lessons from History & Faith',
      duration: ENHANCED_LESSON_PHASES.summary.baseSeconds,
      phaseDescription: 'Summarizing key learnings and their relevance. // TODO: Replace with expert-reviewed World History & Religions content.',
      content: {
        keyTakeaways: [
          `Key learning about [Historical Period/Civilization]. // TODO: Replace with expert-reviewed World History & Religions content.`,
          `Understanding the impact of [Religious Concept/Tradition]. // TODO: Replace with expert-reviewed World History & Religions content.`,
        ],
        nextTopicSuggestion: `Next, we could explore [Related Topic]. // TODO: Replace with expert-reviewed World History & Religions content.`
      },
    },
  ];

  return {
    subject: 'worldHistoryReligions',
    skillArea: 'foundations', // Default skill area
    gradeLevel,
    learningStyle: learningStyle, // Matches EnhancedLessonConfig
    sessionId,
    title: `Placeholder World History & Religions Lesson (Grade ${gradeLevel})`,
    overview: 'This is a placeholder lesson exploring world history and global religions, designed to be adapted for various grade levels. // TODO: Replace with expert-reviewed World History & Religions content.',
    phases: phases,
    estimatedTotalDuration: phases.reduce((sum, phase) => sum + phase.duration, 0),
    learningObjectives: [
      `Understand key aspects of [Specific Historical Topic]. // TODO: Replace with expert-reviewed World History & Religions content.`,
      `Explore main tenets of [Specific Religious Concept]. // TODO: Replace with expert-reviewed World History & Religions content.`
    ],
    materials: ['Device with internet access'],
    assessmentMethods: ['Interactive questions', 'Activity participation', 'Creative output'],
    keywords: ['History', 'Religion', 'Civilization', 'Faith', 'Culture', 'Placeholder'],
    // generatedAt: new Date().toISOString(), // This is typically set by the calling generator like generateEnhancedLesson
  };
};
