-- Populate universes table from the catalog
-- This will insert all UniversePacks from the catalog into the database

INSERT INTO universes (id, title, subject, grade_level, description, metadata, visibility) 
VALUES 
  -- Sample universes based on the catalog structure
  ('urban-farming-venture', 'Urban Farming Venture', 'science', '6-8', 'Start an urban farm business in your neighborhood', '{"category": "Entrepreneurship & Business", "tags": ["farming", "business", "sustainability"], "imagePrompt": "bright kid-friendly urban farm with raised beds and greenhouse, simple shapes, high-contrast"}', 'public'),
  ('space-mission-control', 'Space Mission Control', 'science', '6-8', 'Design and execute a space mission to Mars', '{"category": "Science & Exploration", "tags": ["space", "mission", "engineering"], "imagePrompt": "bright kid-friendly space mission control center with screens and rockets, simple shapes, high-contrast"}', 'public'),
  ('digital-art-studio', 'Digital Art Studio', 'creative-arts', '6-8', 'Create digital artwork and animations', '{"category": "Creative Arts & Media Production", "tags": ["art", "digital", "creativity"], "imagePrompt": "bright kid-friendly digital art studio with tablets and colorful graphics, simple shapes, high-contrast"}', 'public'),
  ('community-garden-project', 'Community Garden Project', 'civics', '6-8', 'Organize a community garden for your neighborhood', '{"category": "Civics, Community & Social Good", "tags": ["community", "garden", "leadership"], "imagePrompt": "bright kid-friendly community garden with diverse people and plants, simple shapes, high-contrast"}', 'public'),
  ('robot-building-lab', 'Robot Building Lab', 'engineering', '6-8', 'Design and build robots to solve real problems', '{"category": "Engineering & Hands-On Design", "tags": ["robotics", "engineering", "problem-solving"], "imagePrompt": "bright kid-friendly robotics lab with colorful robots and tools, simple shapes, high-contrast"}', 'public'),
  ('time-management-academy', 'Time Management Academy', 'life-essentials', '6-8', 'Learn essential time management and productivity skills', '{"category": "Personal Growth & Life Skills", "tags": ["time management", "productivity", "skills"], "imagePrompt": "bright kid-friendly organized study space with clocks and planners, simple shapes, high-contrast"}', 'public'),
  ('marine-biology-expedition', 'Marine Biology Expedition', 'science', '6-8', 'Explore ocean ecosystems and marine life', '{"category": "Science & Exploration", "tags": ["marine biology", "ocean", "exploration"], "imagePrompt": "bright kid-friendly underwater scene with colorful fish and coral, simple shapes, high-contrast"}', 'public'),
  ('photography-documentary', 'Photography Documentary', 'creative-arts', '6-8', 'Create a photo documentary about your community', '{"category": "Creative Arts & Media Production", "tags": ["photography", "documentary", "storytelling"], "imagePrompt": "bright kid-friendly photography studio with cameras and photo displays, simple shapes, high-contrast"}', 'public'),
  ('coding-bootcamp', 'Coding Bootcamp', 'computer-science', '6-8', 'Learn programming through fun projects and games', '{"category": "Engineering & Hands-On Design", "tags": ["coding", "programming", "technology"], "imagePrompt": "bright kid-friendly computer lab with colorful code on screens, simple shapes, high-contrast"}', 'public'),
  ('sustainable-energy-lab', 'Sustainable Energy Lab', 'science', '6-8', 'Experiment with renewable energy sources', '{"category": "Science & Exploration", "tags": ["energy", "sustainability", "renewable"], "imagePrompt": "bright kid-friendly energy lab with solar panels and wind turbines, simple shapes, high-contrast"}', 'public')
ON CONFLICT (id) DO NOTHING;