
-- Create a test user for adaptive learning integration testing with proper UUID
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    '12345678-1234-5678-9012-123456789012',
    'authenticated',
    'authenticated',
    'test-adaptive-learning@example.com',
    '$2a$10$test.encrypted.password.hash.for.testing.purposes.only',
    NOW(),
    NOW(),
    '',
    NOW(),
    '',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"first_name": "Test", "last_name": "User", "role": "student"}',
    FALSE,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
) ON CONFLICT (id) DO NOTHING;

-- Also create a basic profile entry for this test user
INSERT INTO public.profiles (
    id,
    user_id,
    name,
    email,
    created_at,
    updated_at
) VALUES (
    '12345678-1234-5678-9012-123456789012',
    '12345678-1234-5678-9012-123456789012',
    'Test User - Adaptive Learning',
    'test-adaptive-learning@example.com',
    NOW(),
    NOW()
) ON CONFLICT (id) DO NOTHING;
