-- 0) sanity: make sure this user exists (should return 1 row)
-- This is just a check, the actual seeding follows

-- 1) ensure a unique slug index (safe if it already exists)
CREATE UNIQUE INDEX IF NOT EXISTS universes_slug_key ON public.universes(slug);

-- 2) seed universes using the real owner_id from JWT
DO $$
DECLARE
  v_owner uuid := 'ab8d3007-ed4c-4a27-93b9-8cdf6eed1b8b';
BEGIN
  WITH data(slug,title,subject,grade_level,description,metadata) AS (
    VALUES
      ('space-mission-control','Space Mission Control','science','6-8',
       'Design and execute a space mission to Mars',
       '{"category":"Science & Exploration","tags":["space","mission","engineering"],
         "imagePrompt":"bright kid-friendly space mission control center, simple shapes, high-contrast"}'::jsonb),
      ('marine-biology-expedition','Marine Biology Expedition','science','6-8',
       'Explore ocean ecosystems and marine life',
       '{"category":"Science & Exploration","tags":["marine biology","ocean","exploration"],
         "imagePrompt":"bright kid-friendly underwater scene with colorful fish and coral, simple shapes, high-contrast"}'::jsonb),
      ('robot-building-lab','Robot Building Lab','engineering','6-8',
       'Design and build robots to solve real problems',
       '{"category":"Engineering & Hands-On Design","tags":["robotics","engineering","problem-solving"],
         "imagePrompt":"bright kid-friendly robotics lab with colorful robots and tools, simple shapes, high-contrast"}'::jsonb),
      ('community-garden-project','Community Garden Project','civics','6-8',
       'Organize a community garden for your neighborhood',
       '{"category":"Civics, Community & Social Good","tags":["community","garden","leadership"],
         "imagePrompt":"bright kid-friendly community garden, simple shapes, high-contrast"}'::jsonb),
      ('digital-art-studio','Digital Art Studio','creative-arts','6-8',
       'Create digital artwork and animations',
       '{"category":"Creative Arts & Media Production","tags":["art","digital","creativity"],
         "imagePrompt":"bright kid-friendly digital art studio, simple shapes, high-contrast"}'::jsonb),
      ('weather-forecasting-station','Weather Forecasting Station','science','6-8',
       'Build and operate a weather monitoring system',
       '{"category":"Science & Exploration","tags":["weather","meteorology","data"],
         "imagePrompt":"bright kid-friendly weather station with instruments, simple shapes, high-contrast"}'::jsonb),
      ('sustainable-city-design','Sustainable City Design','civics','6-8',
       'Plan an eco-friendly city of the future',
       '{"category":"Civics, Community & Social Good","tags":["sustainability","urban planning","environment"],
         "imagePrompt":"bright kid-friendly sustainable city with green buildings, simple shapes, high-contrast"}'::jsonb),
      ('coding-adventure-game','Coding Adventure Game','computer-science','6-8',
       'Create an interactive adventure game using code',
       '{"category":"Engineering & Hands-On Design","tags":["coding","game development","programming"],
         "imagePrompt":"bright kid-friendly coding workspace with colorful code blocks, simple shapes, high-contrast"}'::jsonb),
      ('music-composition-studio','Music Composition Studio','music','6-8',
       'Compose and produce original music',
       '{"category":"Creative Arts & Media Production","tags":["music","composition","production"],
         "imagePrompt":"bright kid-friendly music studio with instruments and sound equipment, simple shapes, high-contrast"}'::jsonb),
      ('historical-time-machine','Historical Time Machine','history-religion','6-8',
       'Travel through time to explore different historical periods',
       '{"category":"Humanities & Historical Perspective","tags":["history","time travel","exploration"],
         "imagePrompt":"bright kid-friendly time machine with historical artifacts, simple shapes, high-contrast"}'::jsonb),
      ('cooking-chemistry-lab','Cooking Chemistry Lab','science','6-8',
       'Discover the science behind cooking and baking',
       '{"category":"Science & Exploration","tags":["chemistry","cooking","experiments"],
         "imagePrompt":"bright kid-friendly kitchen laboratory with cooking tools and science equipment, simple shapes, high-contrast"}'::jsonb),
      ('documentary-filmmaking','Documentary Filmmaking','creative-arts','6-8',
       'Create a documentary about an important issue',
       '{"category":"Creative Arts & Media Production","tags":["filmmaking","documentary","storytelling"],
         "imagePrompt":"bright kid-friendly film studio with cameras and editing equipment, simple shapes, high-contrast"}'::jsonb),
      ('entrepreneurship-startup','Entrepreneurship Startup','life-essentials','6-8',
       'Start your own business and learn about entrepreneurship',
       '{"category":"Life Skills & Real-World Preparation","tags":["business","entrepreneurship","economics"],
         "imagePrompt":"bright kid-friendly business office with charts and presentation materials, simple shapes, high-contrast"}'::jsonb),
      ('virtual-museum-curator','Virtual Museum Curator','creative-arts','6-8',
       'Curate and design your own virtual museum exhibit',
       '{"category":"Creative Arts & Media Production","tags":["museum","curation","digital design"],
         "imagePrompt":"bright kid-friendly virtual museum with digital displays, simple shapes, high-contrast"}'::jsonb),
      ('renewable-energy-engineer','Renewable Energy Engineer','engineering','6-8',
       'Design renewable energy solutions for communities',
       '{"category":"Engineering & Hands-On Design","tags":["renewable energy","engineering","sustainability"],
         "imagePrompt":"bright kid-friendly renewable energy lab with solar panels and wind turbines, simple shapes, high-contrast"}'::jsonb),
      ('language-exchange-program','Language Exchange Program','languages','6-8',
       'Connect with students worldwide to learn new languages',
       '{"category":"Global Connections & Cultural Exchange","tags":["languages","cultural exchange","communication"],
         "imagePrompt":"bright kid-friendly language classroom with flags and cultural symbols, simple shapes, high-contrast"}'::jsonb),
      ('wildlife-conservation-project','Wildlife Conservation Project','science','6-8',
       'Protect endangered species and their habitats',
       '{"category":"Science & Exploration","tags":["wildlife","conservation","biology"],
         "imagePrompt":"bright kid-friendly wildlife sanctuary with diverse animals, simple shapes, high-contrast"}'::jsonb),
      ('mathematics-escape-room','Mathematics Escape Room','mathematics','6-8',
       'Design puzzle-based escape rooms using math concepts',
       '{"category":"STEM Challenges & Problem Solving","tags":["mathematics","puzzles","problem solving"],
         "imagePrompt":"bright kid-friendly escape room with mathematical puzzles, simple shapes, high-contrast"}'::jsonb),
      ('mindfulness-wellness-center','Mindfulness Wellness Center','mental-wellness','6-8',
       'Create a space for mental health and wellness activities',
       '{"category":"Life Skills & Real-World Preparation","tags":["mindfulness","wellness","mental health"],
         "imagePrompt":"bright kid-friendly wellness center with calm colors and peaceful elements, simple shapes, high-contrast"}'::jsonb),
      ('space-archaeology-mission','Space Archaeology Mission','science','6-8',
       'Discover ancient civilizations using space technology',
       '{"category":"Science & Exploration","tags":["archaeology","space","ancient civilizations"],
         "imagePrompt":"bright kid-friendly space archaeological site with artifacts and technology, simple shapes, high-contrast"}'::jsonb),
      ('creative-writing-workshop','Creative Writing Workshop','languages','6-8',
       'Write and publish your own stories and poems',
       '{"category":"Creative Arts & Media Production","tags":["writing","creativity","storytelling"],
         "imagePrompt":"bright kid-friendly writing workshop with books and writing materials, simple shapes, high-contrast"}'::jsonb),
      ('sports-science-lab','Sports Science Lab','body-lab','6-8',
       'Study the science behind athletic performance',
       '{"category":"Health, Fitness & Body Science","tags":["sports science","athletics","health"],
         "imagePrompt":"bright kid-friendly sports science lab with athletic equipment and measurement tools, simple shapes, high-contrast"}'::jsonb),
      ('environmental-detective','Environmental Detective','science','6-8',
       'Investigate environmental mysteries in your community',
       '{"category":"Science & Exploration","tags":["environment","investigation","ecology"],
         "imagePrompt":"bright kid-friendly environmental investigation scene with nature and scientific tools, simple shapes, high-contrast"}'::jsonb),
      ('cultural-festival-organizer','Cultural Festival Organizer','civics','6-8',
       'Plan and organize a multicultural community festival',
       '{"category":"Civics, Community & Social Good","tags":["culture","festival","community"],
         "imagePrompt":"bright kid-friendly cultural festival with diverse decorations and activities, simple shapes, high-contrast"}'::jsonb),
      ('invention-workshop','Invention Workshop','engineering','6-8',
       'Invent solutions to everyday problems',
       '{"category":"Engineering & Hands-On Design","tags":["invention","innovation","problem solving"],
         "imagePrompt":"bright kid-friendly invention workshop with tools and prototypes, simple shapes, high-contrast"}'::jsonb)
  )
  INSERT INTO public.universes
    (id, owner_id, slug, title, subject, grade_level, description, metadata, visibility)
  SELECT
    gen_random_uuid(), v_owner, d.slug, d.title, d.subject, d.grade_level, d.description, d.metadata, 'public'
  FROM data d
  ON CONFLICT (slug) DO NOTHING;
END $$;