-- Update universe_images table structure for better tracking
ALTER TABLE public.universe_images 
ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'ai';

-- Add comments for clarity
COMMENT ON COLUMN public.universe_images.source IS 'Source of image: ai, fallback, or manual';
COMMENT ON COLUMN public.universe_images.is_ai_generated IS 'Whether image was generated by AI (legacy column)';

-- Track bulk-job progress and errors
CREATE TABLE IF NOT EXISTS public.universe_image_jobs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  finished_at TIMESTAMP WITH TIME ZONE,
  total INTEGER NOT NULL DEFAULT 0,
  success INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  skipped INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on jobs table
ALTER TABLE public.universe_image_jobs ENABLE ROW LEVEL SECURITY;

-- Create policy for jobs table
CREATE POLICY "Service role can manage universe image jobs" 
ON public.universe_image_jobs 
FOR ALL 
USING (true)
WITH CHECK (true);

-- Add index for better performance
CREATE INDEX IF NOT EXISTS idx_universe_images_universe_lang ON public.universe_images(universe_id, lang);
CREATE INDEX IF NOT EXISTS idx_universe_image_jobs_started_at ON public.universe_image_jobs(started_at DESC);