-- First, add a system user for universe ownership (using a fixed UUID)
-- Then populate the universes table with proper data

-- Insert 30 sample universes with proper owner_id
DO $$
DECLARE
    system_owner_id UUID := '00000000-0000-0000-0000-000000000001';
BEGIN
    INSERT INTO universes (id, owner_id, title, subject, grade_level, description, metadata, visibility) VALUES
    -- Entrepreneurship & Business (5 universes)
    (gen_random_uuid(), system_owner_id, 'Urban Farming Venture', 'science', '6-8', 'Start an urban farm business in your neighborhood', '{"category": "Entrepreneurship & Business", "slug": "urban-farming-venture", "tags": ["farming", "business", "sustainability"], "imagePrompt": "bright kid-friendly urban farm with raised beds and greenhouse, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Teen Tech Startup', 'computer-science', '6-8', 'Launch your own technology startup', '{"category": "Entrepreneurship & Business", "slug": "teen-tech-startup", "tags": ["technology", "startup", "innovation"], "imagePrompt": "bright kid-friendly tech startup office with computers and whiteboards, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'School Store Empire', 'mathematics', '6-8', 'Run a profitable school store business', '{"category": "Entrepreneurship & Business", "slug": "school-store-empire", "tags": ["business", "retail", "finance"], "imagePrompt": "bright kid-friendly school store with shelves and cash register, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Local Food Truck', 'life-essentials', '6-8', 'Design and operate a food truck business', '{"category": "Entrepreneurship & Business", "slug": "local-food-truck", "tags": ["food", "business", "marketing"], "imagePrompt": "bright kid-friendly colorful food truck with serving window, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Eco-Friendly Cleaning Co', 'science', '6-8', 'Start an environmentally conscious cleaning service', '{"category": "Entrepreneurship & Business", "slug": "eco-friendly-cleaning-co", "tags": ["environment", "business", "sustainability"], "imagePrompt": "bright kid-friendly green cleaning supplies and equipment, simple shapes, high-contrast"}', 'public'),

    -- Science & Exploration (5 universes)
    (gen_random_uuid(), system_owner_id, 'Space Mission Control', 'science', '6-8', 'Design and execute a space mission to Mars', '{"category": "Science & Exploration", "slug": "space-mission-control", "tags": ["space", "mission", "engineering"], "imagePrompt": "bright kid-friendly space mission control center with screens and rockets, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Marine Biology Expedition', 'science', '6-8', 'Explore ocean ecosystems and marine life', '{"category": "Science & Exploration", "slug": "marine-biology-expedition", "tags": ["marine biology", "ocean", "exploration"], "imagePrompt": "bright kid-friendly underwater scene with colorful fish and coral, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Weather Station Network', 'science', '6-8', 'Build a network of weather monitoring stations', '{"category": "Science & Exploration", "slug": "weather-station-network", "tags": ["weather", "data", "monitoring"], "imagePrompt": "bright kid-friendly weather station with instruments and clouds, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Volcano Research Lab', 'science', '6-8', 'Study volcanic activity and predict eruptions', '{"category": "Science & Exploration", "slug": "volcano-research-lab", "tags": ["geology", "volcanoes", "research"], "imagePrompt": "bright kid-friendly volcano with research equipment, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Arctic Wildlife Survey', 'science', '6-8', 'Document Arctic wildlife and climate change', '{"category": "Science & Exploration", "slug": "arctic-wildlife-survey", "tags": ["wildlife", "arctic", "conservation"], "imagePrompt": "bright kid-friendly Arctic scene with polar bears and ice, simple shapes, high-contrast"}', 'public'),

    -- Creative Arts & Media Production (5 universes)
    (gen_random_uuid(), system_owner_id, 'Digital Art Studio', 'creative-arts', '6-8', 'Create digital artwork and animations', '{"category": "Creative Arts & Media Production", "slug": "digital-art-studio", "tags": ["art", "digital", "creativity"], "imagePrompt": "bright kid-friendly digital art studio with tablets and colorful graphics, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Photography Documentary', 'creative-arts', '6-8', 'Create a photo documentary about your community', '{"category": "Creative Arts & Media Production", "slug": "photography-documentary", "tags": ["photography", "documentary", "storytelling"], "imagePrompt": "bright kid-friendly photography studio with cameras and photo displays, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Student News Network', 'creative-arts', '6-8', 'Produce news content for your school', '{"category": "Creative Arts & Media Production", "slug": "student-news-network", "tags": ["journalism", "media", "communication"], "imagePrompt": "bright kid-friendly news studio with cameras and microphones, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Animation Workshop', 'creative-arts', '6-8', 'Create animated stories and characters', '{"category": "Creative Arts & Media Production", "slug": "animation-workshop", "tags": ["animation", "storytelling", "character design"], "imagePrompt": "bright kid-friendly animation studio with drawing tablets and characters, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Music Production Lab', 'creative-arts', '6-8', 'Compose and produce original music', '{"category": "Creative Arts & Media Production", "slug": "music-production-lab", "tags": ["music", "production", "creativity"], "imagePrompt": "bright kid-friendly music studio with instruments and recording equipment, simple shapes, high-contrast"}', 'public'),

    -- Civics, Community & Social Good (5 universes)
    (gen_random_uuid(), system_owner_id, 'Community Garden Project', 'civics', '6-8', 'Organize a community garden for your neighborhood', '{"category": "Civics, Community & Social Good", "slug": "community-garden-project", "tags": ["community", "garden", "leadership"], "imagePrompt": "bright kid-friendly community garden with diverse people and plants, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Youth Climate Council', 'civics', '6-8', 'Lead environmental initiatives in your community', '{"category": "Civics, Community & Social Good", "slug": "youth-climate-council", "tags": ["climate", "leadership", "environment"], "imagePrompt": "bright kid-friendly council meeting with recycling and green symbols, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Neighborhood Safety Patrol', 'civics', '6-8', 'Improve safety and security in your area', '{"category": "Civics, Community & Social Good", "slug": "neighborhood-safety-patrol", "tags": ["safety", "community", "responsibility"], "imagePrompt": "bright kid-friendly neighborhood scene with safety equipment, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Food Bank Organizer', 'civics', '6-8', 'Coordinate food distribution for those in need', '{"category": "Civics, Community & Social Good", "slug": "food-bank-organizer", "tags": ["food security", "charity", "organization"], "imagePrompt": "bright kid-friendly food bank with volunteers and food boxes, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Student Government', 'civics', '6-8', 'Participate in democratic governance at school', '{"category": "Civics, Community & Social Good", "slug": "student-government", "tags": ["democracy", "leadership", "governance"], "imagePrompt": "bright kid-friendly student council meeting with voting booth, simple shapes, high-contrast"}', 'public'),

    -- Engineering & Hands-On Design (5 universes)
    (gen_random_uuid(), system_owner_id, 'Robot Building Lab', 'engineering', '6-8', 'Design and build robots to solve real problems', '{"category": "Engineering & Hands-On Design", "slug": "robot-building-lab", "tags": ["robotics", "engineering", "problem-solving"], "imagePrompt": "bright kid-friendly robotics lab with colorful robots and tools, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Bridge Engineering Challenge', 'engineering', '6-8', 'Design bridges to connect communities', '{"category": "Engineering & Hands-On Design", "slug": "bridge-engineering-challenge", "tags": ["engineering", "construction", "design"], "imagePrompt": "bright kid-friendly bridge construction site with blueprints, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Renewable Energy Systems', 'engineering', '6-8', 'Build solar and wind energy solutions', '{"category": "Engineering & Hands-On Design", "slug": "renewable-energy-systems", "tags": ["renewable energy", "engineering", "sustainability"], "imagePrompt": "bright kid-friendly solar panels and wind turbines, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'App Development Studio', 'computer-science', '6-8', 'Create mobile apps to solve problems', '{"category": "Engineering & Hands-On Design", "slug": "app-development-studio", "tags": ["programming", "mobile apps", "technology"], "imagePrompt": "bright kid-friendly computer screen with colorful app interfaces, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Mechanical Workshop', 'engineering', '6-8', 'Build and repair mechanical devices', '{"category": "Engineering & Hands-On Design", "slug": "mechanical-workshop", "tags": ["mechanics", "repair", "hands-on"], "imagePrompt": "bright kid-friendly workshop with tools and mechanical parts, simple shapes, high-contrast"}', 'public'),

    -- Personal Growth & Life Skills (5 universes)
    (gen_random_uuid(), system_owner_id, 'Time Management Academy', 'life-essentials', '6-8', 'Learn essential time management and productivity skills', '{"category": "Personal Growth & Life Skills", "slug": "time-management-academy", "tags": ["time management", "productivity", "skills"], "imagePrompt": "bright kid-friendly organized study space with clocks and planners, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Financial Literacy Lab', 'mathematics', '6-8', 'Master personal finance and budgeting', '{"category": "Personal Growth & Life Skills", "slug": "financial-literacy-lab", "tags": ["finance", "budgeting", "money management"], "imagePrompt": "bright kid-friendly bank scene with coins and calculator, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Public Speaking Club', 'languages', '6-8', 'Develop confidence in public speaking', '{"category": "Personal Growth & Life Skills", "slug": "public-speaking-club", "tags": ["communication", "confidence", "presentation"], "imagePrompt": "bright kid-friendly stage with microphone and audience, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Mindfulness Center', 'mental-wellness', '6-8', 'Practice mindfulness and stress management', '{"category": "Personal Growth & Life Skills", "slug": "mindfulness-center", "tags": ["mindfulness", "wellness", "stress management"], "imagePrompt": "bright kid-friendly peaceful meditation space with plants, simple shapes, high-contrast"}', 'public'),
    (gen_random_uuid(), system_owner_id, 'Leadership Academy', 'life-essentials', '6-8', 'Develop leadership skills and teamwork', '{"category": "Personal Growth & Life Skills", "slug": "leadership-academy", "tags": ["leadership", "teamwork", "development"], "imagePrompt": "bright kid-friendly group meeting with leadership symbols, simple shapes, high-contrast"}', 'public')
    ON CONFLICT (id) DO NOTHING;
END $$;